algoritmo "Maior e menor ex02"
var

   num1, num2 : inteiro

inicio

   escreva("escreva um numero:")
   leia(num1)
   escreva("escreva outro numero:")
   leia(num2)

   se num1 > num2 entao
      escreva("o maior numero é:", num1)
   senao
      se num2 > num1 entao
         escreva("o maior numero é:", num2)
      senao
         escreval("Os numero sao iguais")

      fimse
   fimse



fimalgoritmo