Algoritmo "Media"
Var
// Seção de Declarações das variáveis 
n1: inteiro
n2: inteiro
n3: inteiro
media: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite sua primeira nota: ")
leia(n1)

escreva("Digite sua primeira nota: ")
leia(n2)

escreva("Digite sua primeira nota: ")
leia(n3)

media <- (n1 + n2 + n3)/3
escreva("A média de suas notas é: ", media)

Fimalgoritmo