algoritmo "semnome"
var

   cont, n2, numeroP, parar : inteiro


inicio

   numerop := 1
   cont := 0
   n2 := 1

   enquanto numerop > 0 faca
      escreva("Digite um Numero:")
      leia( numerop )
      se numerop > 0 entao
         cont <- cont + 1
      senao
         escreval("O numero de numeros utilizados para conseguir um numero >< de 0 foi",cont,)
      fimse
fimenquanto




fimalgoritmo