algoritmo "semnome"
var

 a, b, soma, diferenca, produto, divi: real
 

inicio

      escreva("Digite um valor para a: ")
      leia (a)
      escreva("Digite um valor para B: ")
      leia (b)
      soma <- a+b
      diferenca <- a-b
      produto <- a*b
      divi <- a/b
      escreval("soma.:", soma)
      escreval("diferenca.:", diferenca)
      escreval("produto.:", produto)
      escreval("divisao.:", divi)





fimalgoritmo